/**
 * @packageDocumentation
 * @module api.functional.connector.kakao_talk.message
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IKakaoTalk } from "../../../../structures/connector/kakao_talk/IKakaoTalk";

/**
 * @controller KakaoTalkController.send
 * @path POST /connector/kakao-talk/message
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function send(
  connection: IConnection,
  input: send.Input,
): Promise<send.Output> {
  return !!connection.simulate
    ? send.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...send.METADATA,
          template: send.METADATA.path,
          path: send.path(),
        },
        input,
      );
}
export namespace send {
  export type Input = Primitive<IKakaoTalk.ISendKakaoTalkToFriendsInput>;
  export type Output = Primitive<IKakaoTalk.ISendKakaoTalkToFriendsOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/kakao-talk/message",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/kakao-talk/message";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IKakaoTalk.ISendKakaoTalkToFriendsOutput>> =>
    typia.random<Primitive<IKakaoTalk.ISendKakaoTalkToFriendsOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: send.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
