/**
 * @packageDocumentation
 * @module api.functional.connector.figma
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as get_files from "./get_files";
export * as comments from "./comments";
