/**
 * @packageDocumentation
 * @module api.functional.connector.marketing_copy.generate_copy_image
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type {
  IMarketingCopyGenerator,
  IMarketingCopyImage,
} from "../../../../structures/connector/marketing/IMarketingCopyGenerator";

/**
 * 주어진 입력으로부터 마케팅 카피 이미지를 생성합니다.
 *
 * @param input 마케팅 카피 이미지 생성을 위한 입력
 * @summary 마케팅 카피 이미지 생성
 * @returns 생성된 마케팅 카피 이미지
 * @tag Llm 마케팅 카피 이미지 생성
 *
 * @controller MarketingCopyController.generateCopyImage
 * @path POST /connector/marketing-copy/generate-copy-image
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function generateCopyImage(
  connection: IConnection,
  input: generateCopyImage.Input,
): Promise<generateCopyImage.Output> {
  return !!connection.simulate
    ? generateCopyImage.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...generateCopyImage.METADATA,
          template: generateCopyImage.METADATA.path,
          path: generateCopyImage.path(),
        },
        input,
      );
}
export namespace generateCopyImage {
  export type Input =
    Primitive<IMarketingCopyGenerator.IGenerateMarketingCopyImageInput>;
  export type Output = Primitive<IMarketingCopyImage>;

  export const METADATA = {
    method: "POST",
    path: "/connector/marketing-copy/generate-copy-image",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/marketing-copy/generate-copy-image";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IMarketingCopyImage>> =>
    typia.random<Primitive<IMarketingCopyImage>>(g);
  export const simulate = (
    connection: IConnection,
    input: generateCopyImage.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
