/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads.campaigns.ads.get_details
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleAds } from "../../../../../../structures/connector/google_ads/IGoogleAds";

/**
 * 광고의 상세를 조회해요
 *
 * @param input 광고 상세 조회 조건
 * @summary 광고 상세 조회
 * @returns 광고 상세
 *
 * @controller GoogleAdsController.getAdGroupAdDetail
 * @path POST /connector/google-ads/campaigns/ads/get-details
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAdGroupAdDetail(
  connection: IConnection,
  input: getAdGroupAdDetail.Input,
): Promise<getAdGroupAdDetail.Output> {
  return !!connection.simulate
    ? getAdGroupAdDetail.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getAdGroupAdDetail.METADATA,
          template: getAdGroupAdDetail.METADATA.path,
          path: getAdGroupAdDetail.path(),
        },
        input,
      );
}
export namespace getAdGroupAdDetail {
  export type Input = Primitive<IGoogleAds.IGetAdGroupAdDetailInput>;
  export type Output = Primitive<IGoogleAds.IGetAdGroupAdDetailOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-ads/campaigns/ads/get-details",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-ads/campaigns/ads/get-details";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IGoogleAds.IGetAdGroupAdDetailOutput>> =>
    typia.random<Primitive<IGoogleAds.IGetAdGroupAdDetailOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: getAdGroupAdDetail.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
