# Use postgres/example user/password credentials
version: "3.9"
services:
  db:
    image: postgres
    container_name: connector-test-db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "6544:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
