/**
 * @packageDocumentation
 * @module api.functional.connector.story_generator
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type {
  IStoryGeneratorRequest,
  IStoryGeneratorResponse,
} from "../../../structures/connector/story_generator/IStoryGenerator";

/**
 * 유저의 입력을 기반으로 스토리를 짭니다.
 *
 * @param input 스토리 생성을 위한 입력
 * @summary 스토리 생성
 * @returns 생성된 스토리 혹은 추가 정보 요청
 * @tag Llm 스토리 생성
 *
 * @controller StoryGeneratorController.generate
 * @path POST /connector/story-generator
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function generate(
  connection: IConnection,
  input: generate.Input,
): Promise<generate.Output> {
  return !!connection.simulate
    ? generate.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...generate.METADATA,
          template: generate.METADATA.path,
          path: generate.path(),
        },
        input,
      );
}
export namespace generate {
  export type Input = Primitive<IStoryGeneratorRequest>;
  export type Output = Primitive<IStoryGeneratorResponse>;

  export const METADATA = {
    method: "POST",
    path: "/connector/story-generator",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/story-generator";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IStoryGeneratorResponse>> =>
    typia.random<Primitive<IStoryGeneratorResponse>>(g);
  export const simulate = (
    connection: IConnection,
    input: generate.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
