/**
 * @packageDocumentation
 * @module api.functional.connector.typeform.forms.fields
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { ITypeform } from "../../../../../structures/connector/typeform/ITypeform";

/**
 * 랭킹, 드롭다운, 다중선택 질문의 옵션을 업데이트 할 폼의 필드 정보 가져오기.
 *
 * @param formId 업데이트 할 폼의 ID.
 * @summary 타입폼 업데이트 할 폼의 필드 정보 가져오기.
 * @returns 폼의 필드 ID와 필드명.
 * @tag Typeform
 * @tag 타입폼
 * @tag 설문조사
 * @tag 온라인 폼
 * @tag 설문지
 * @tag 고객 만족도 조사
 * @tag 설문 양식
 * @tag 퀴즈
 * @tag 응답 확인
 * @tag 응답 관리
 * @tag 응답자 관리
 * @tag 설문 분석
 * @tag 응답 데이터
 * @tag 설문지 템플릿
 * @tag 설문 응답
 * @tag 설문지 공유
 * @tag 설문조사 결과
 * @tag 질문지 작성
 * @tag 인터뷰 신청
 * @tag 응답 수집
 * @tag 행사
 * @tag 피드백
 * @tag 사용자 조사
 * @tag 이벤트 피드백
 * @tag 행사 피드백
 * @tag Survey
 * @tag Online Form
 * @tag Questionnaire
 * @tag Customer Satisfaction Survey
 * @tag Survey Form
 * @tag Quiz
 * @tag Survey Responses
 * @tag Manage Responses
 * @tag Manage Respondents
 * @tag Survey Analysis
 * @tag Response Data
 * @tag Survey Template
 * @tag Survey Answers
 * @tag Share Survey
 * @tag Survey Results
 * @tag Create Questionnaire
 * @tag Interview Application
 * @tag Collect Responses
 * @tag Event
 * @tag Feedback
 * @tag User Survey
 * @tag Event Feedback
 * @internal
 *
 * @controller TypeformController.getFieldsForUpdateFieldValue
 * @path GET /connector/typeform/forms/:formId/fields
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getFieldsForUpdateFieldValue(
  connection: IConnection,
  formId: string,
): Promise<getFieldsForUpdateFieldValue.Output> {
  return !!connection.simulate
    ? getFieldsForUpdateFieldValue.simulate(connection, formId)
    : PlainFetcher.fetch(connection, {
        ...getFieldsForUpdateFieldValue.METADATA,
        template: getFieldsForUpdateFieldValue.METADATA.path,
        path: getFieldsForUpdateFieldValue.path(formId),
      });
}
export namespace getFieldsForUpdateFieldValue {
  export type Output = Primitive<
    Array<ITypeform.IFieldInfoForUpdateFieldValueOutput>
  >;

  export const METADATA = {
    method: "GET",
    path: "/connector/typeform/forms/:formId/fields",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (formId: string) =>
    `/connector/typeform/forms/${encodeURIComponent(formId ?? "null")}/fields`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<
    Primitive<Array<ITypeform.IFieldInfoForUpdateFieldValueOutput>>
  > =>
    typia.random<
      Primitive<Array<ITypeform.IFieldInfoForUpdateFieldValueOutput>>
    >(g);
  export const simulate = (connection: IConnection, formId: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(formId),
      contentType: "application/json",
    });
    assert.param("formId")(() => typia.assert(formId));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
