/**
 * @packageDocumentation
 * @module api.functional.connector.notion.get.database_info
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { ICommon } from "../../../../../structures/connector/common/ISecretValue";
import type { INotion } from "../../../../../structures/connector/notion/INotion";

/**
 * Get Database list Info for create Item in database.
 *
 * @returns array of databaseId, database title, database properties info
 * @tag Notion
 *
 * @controller NotionController.getDatabaseListInfo
 * @path POST /connector/notion/get/database-info
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getDatabaseListInfo(
  connection: IConnection,
  input: getDatabaseListInfo.Input,
): Promise<getDatabaseListInfo.Output> {
  return !!connection.simulate
    ? getDatabaseListInfo.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getDatabaseListInfo.METADATA,
          path: getDatabaseListInfo.path(),
        },
        input,
      );
}
export namespace getDatabaseListInfo {
  export type Input = Primitive<ICommon.ISecret<"Notion", never>>;
  export type Output = Primitive<Array<INotion.IDatabaseInfo>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/notion/get/database-info",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/notion/get/database-info";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Array<INotion.IDatabaseInfo>>> =>
    typia.random<Primitive<Array<INotion.IDatabaseInfo>>>(g);
  export const simulate = (
    connection: IConnection,
    input: getDatabaseListInfo.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Get Database Info for create Item in database.
 *
 * @param databaseId
 * @returns databaseId, database title, database properties info
 * @tag Notion
 *
 * @controller NotionController.getDatabaseInfo
 * @path POST /connector/notion/get/database-info/:databaseId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getDatabaseInfo(
  connection: IConnection,
  input: getDatabaseInfo.Input,
  databaseId: string,
): Promise<getDatabaseInfo.Output> {
  return !!connection.simulate
    ? getDatabaseInfo.simulate(connection, input, databaseId)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getDatabaseInfo.METADATA,
          path: getDatabaseInfo.path(databaseId),
        },
        input,
      );
}
export namespace getDatabaseInfo {
  export type Input = Primitive<ICommon.ISecret<"Notion", never>>;
  export type Output = Primitive<INotion.IDatabaseInfo>;

  export const METADATA = {
    method: "POST",
    path: "/connector/notion/get/database-info/:databaseId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (databaseId: string) =>
    `/connector/notion/get/database-info/${encodeURIComponent(databaseId ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<INotion.IDatabaseInfo>> =>
    typia.random<Primitive<INotion.IDatabaseInfo>>(g);
  export const simulate = (
    connection: IConnection,
    input: getDatabaseInfo.Input,
    databaseId: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(databaseId),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    assert.param("databaseId")(() => typia.assert(databaseId));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
