/**
 * @packageDocumentation
 * @module api.functional.connector.imweb.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { Try } from "../../../../../utils/createResponseForm";
import type { IImweb } from "../../../../structures/connector/imweb/IImweb";

/**
 * 아임웹 액세스 토큰 발급.
 *
 * @internal
 * @param input 액세스 토큰 발급을 위한 요청 DTO.
 * @returns 액세스 토큰을 담은 응답 DTO.
 *
 * @controller ImwebController.authorization
 * @path POST /connector/imweb/auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function authorization(
  connection: IConnection,
  input: authorization.Input,
): Promise<authorization.Output> {
  return !!connection.simulate
    ? authorization.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...authorization.METADATA,
          template: authorization.METADATA.path,
          path: authorization.path(),
        },
        input,
      );
}
export namespace authorization {
  export type Input = Primitive<IImweb.Credential>;
  export type Output = Primitive<Try<IImweb.IGetAccessTokenOutput>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/imweb/auth",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/imweb/auth";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Try<IImweb.IGetAccessTokenOutput>>> =>
    typia.random<Primitive<Try<IImweb.IGetAccessTokenOutput>>>(g);
  export const simulate = (
    connection: IConnection,
    input: authorization.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
