/**
 * @packageDocumentation
 * @module api.functional.connector.aws.file.upload_url
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Resolved, Primitive } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IAws } from "../../../../../structures/connector/aws/IAws";

/**
 * 파일 업로드를 하기 위해 필요한 URL을 생성합니다.
 *
 * @summary 파일 업로드 URL 생성
 * @Query 파일 확장자
 * @tag AWS
 * @internal
 *
 * @controller AwsController.getUploadUrl
 * @path GET /connector/aws/file/upload-url
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUploadUrl(
  connection: IConnection,
  extension: getUploadUrl.Query,
): Promise<getUploadUrl.Output> {
  return !!connection.simulate
    ? getUploadUrl.simulate(connection, extension)
    : PlainFetcher.fetch(connection, {
        ...getUploadUrl.METADATA,
        path: getUploadUrl.path(extension),
      });
}
export namespace getUploadUrl {
  export type Query = Resolved<IAws.IGetPutObjectUrlInput>;
  export type Output = Primitive<IAws.IGetPutObjectUrlOutput>;

  export const METADATA = {
    method: "GET",
    path: "/connector/aws/file/upload-url",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (extension: getUploadUrl.Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(extension as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/connector/aws/file/upload-url";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IAws.IGetPutObjectUrlOutput>> =>
    typia.random<Primitive<IAws.IGetPutObjectUrlOutput>>(g);
  export const simulate = (
    connection: IConnection,
    extension: getUploadUrl.Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(extension),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(extension));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
