/**
 * @packageDocumentation
 * @module api.functional.connector.google_drive
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleDrive } from "../../../structures/connector/google_drive/IGoogleDrive";

export * as get from "./get";
export * as folder from "./folder";
export * as file from "./file";

/**
 * 파일 또는 폴더에 접근하기 위한 권한을 부여합니다.
 *
 * @summary 구글 드라이브 권한 부여.
 * @param input 권한 부여를 위한 정보.
 * @tag Google Drive
 * @internal
 *
 * @controller GoogleDriveController.permission
 * @path POST /connector/google-drive/permission
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function permission(
  connection: IConnection,
  input: permission.Input,
): Promise<void> {
  return !!connection.simulate
    ? permission.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...permission.METADATA,
          path: permission.path(),
        },
        input,
      );
}
export namespace permission {
  export type Input = Primitive<IGoogleDrive.IPermissionGoogleDriveInput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-drive/permission",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-drive/permission";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<void>> => typia.random<Primitive<void>>(g);
  export const simulate = (
    connection: IConnection,
    input: permission.Input,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
