/**
 * @packageDocumentation
 * @module api.functional.internal.google
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

/**
 * 구글 access token 재발급 요청
 *
 * @internal
 *
 * @controller GoogleController.refreshAccessToken
 * @path GET /internal/google
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function refreshAccessToken(
  connection: IConnection,
): Promise<refreshAccessToken.Output> {
  return !!connection.simulate
    ? refreshAccessToken.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...refreshAccessToken.METADATA,
        path: refreshAccessToken.path(),
      });
}
export namespace refreshAccessToken {
  export type Output = Primitive<string>;

  export const METADATA = {
    method: "GET",
    path: "/internal/google",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/internal/google";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<string>> => typia.random<Primitive<string>>(g);
  export const simulate = (connection: IConnection): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
