/**
 * @packageDocumentation
 * @module api.functional.connector.google_calendar.get_events
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { Try } from "../../../../../utils/createResponseForm";
import type { IGoogleCalendar } from "../../../../structures/connector/google_calendar/IGoogleCalendar";

/**
 * 구글 캘린더에 있는 이벤트 목록을 가져옵니다.
 *
 * @summary 구글 캘린더 이벤트 목록 가져오기.
 * @param calendarId 이벤트 목록을 가져올 캘린더 고유 ID.
 * @param input 이벤트 목록을 가져오기 위한 조건.
 * @returns 구글 캘린더 이벤트 목록.
 * @tag Google-Calendar
 * @tag 구글 캘린더
 * @tag 캘린더
 * @tag 일정 관리
 * @tag 일정 추가
 * @tag 일정 생성
 * @tag 일정 공유
 * @tag 일정 알림
 * @tag 회의 추가
 * @tag 약속 추가
 * @tag 시간 관리
 * @tag 달력
 * @tag 스케줄 관리
 * @tag 일정 조정
 * @tag 반복 일정
 * @tag 일정 동기화
 * @tag 일정 초대
 * @tag 일정 리마인더
 * @tag 캘린더 공유
 * @tag 시간표
 * @tag 구글 일정
 * @tag 스케줄러
 * @tag 이번 주 일정
 * @tag 다음 주 일정
 * @tag 월간 일정
 * @tag 개인 일정
 * @tag 팀 일정
 * @tag 회의 예약
 * @tag 업무 캘린더
 * @tag 휴가 일정
 * @tag Google Calendar
 * @tag Calendar
 * @tag Manage Schedule
 * @tag Add Event
 * @tag Create Event
 * @tag Share Event
 * @tag Event Reminder
 * @tag Add Meeting
 * @tag Add Appointment
 * @tag Time Management
 * @tag Schedule Management
 * @tag Adjust Schedule
 * @tag Recurring Event
 * @tag Sync Calendar
 * @tag Invite to Event
 * @tag Share Calendar
 * @tag Timetable
 * @tag Google Schedule
 * @tag Scheduler
 * @tag This Week's Schedule
 * @tag Next Week's Schedule
 * @tag Monthly Schedule
 * @tag Personal Schedule
 * @tag Team Schedule
 * @tag Schedule Meeting
 * @tag Work Calendar
 * @tag Vacation Schedule
 *
 * @controller GoogleCalendarController.readEvents
 * @path POST /connector/google-calendar/:calendarId/get-events
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function readEvents(
  connection: IConnection,
  calendarId: string,
  input: readEvents.Input,
): Promise<readEvents.Output> {
  return !!connection.simulate
    ? readEvents.simulate(connection, calendarId, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...readEvents.METADATA,
          template: readEvents.METADATA.path,
          path: readEvents.path(calendarId),
        },
        input,
      );
}
export namespace readEvents {
  export type Input = Primitive<IGoogleCalendar.IReadGoogleCalendarEventInput>;
  export type Output = Primitive<
    Try<IGoogleCalendar.IReadGoogleCalendarEventOutput>
  >;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-calendar/:calendarId/get-events",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (calendarId: string) =>
    `/connector/google-calendar/${encodeURIComponent(calendarId ?? "null")}/get-events`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Try<IGoogleCalendar.IReadGoogleCalendarEventOutput>>> =>
    typia.random<
      Primitive<Try<IGoogleCalendar.IReadGoogleCalendarEventOutput>>
    >(g);
  export const simulate = (
    connection: IConnection,
    calendarId: string,
    input: readEvents.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(calendarId),
      contentType: "application/json",
    });
    assert.param("calendarId")(() => typia.assert(calendarId));
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
