/**
 * @packageDocumentation
 * @module api.functional.connector.kakao_navi
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as get_future_directions from "./get_future_directions";
