/**
 * @packageDocumentation
 * @module api.functional.connector.discord.channel.message
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IDiscord } from "../../../../../structures/connector/discord/IDiscord";

/**
 * @controller DiscordController.sendMessage
 * @path POST /connector/discord/channel/message
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function sendMessage(
  connection: IConnection,
  input: sendMessage.Input,
): Promise<sendMessage.Output> {
  return !!connection.simulate
    ? sendMessage.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...sendMessage.METADATA,
          path: sendMessage.path(),
        },
        input,
      );
}
export namespace sendMessage {
  export type Input = Primitive<IDiscord.IDiscordMessageInput>;
  export type Output = Primitive<IDiscord.IDiscordMessageOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/discord/channel/message",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/discord/channel/message";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IDiscord.IDiscordMessageOutput>> =>
    typia.random<Primitive<IDiscord.IDiscordMessageOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: sendMessage.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
