/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads.campaigns.ads.keywords
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleAds } from "../../../../../../structures/connector/google_ads/IGoogleAds";

/**
 * 구글 고객 계정의 광고에 검색 키워드를 추가해요
 *
 * @param input 키워드 추가 조건
 * @summary 광고에 키워드를 추가해요
 * @returns
 *
 * @controller GoogleAdsController.addKeyword
 * @path POST /connector/google-ads/campaigns/ads/keywords
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function addKeyword(
  connection: IConnection,
  input: addKeyword.Input,
): Promise<addKeyword.Output> {
  return !!connection.simulate
    ? addKeyword.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...addKeyword.METADATA,
          template: addKeyword.METADATA.path,
          path: addKeyword.path(),
        },
        input,
      );
}
export namespace addKeyword {
  export type Input = Primitive<IGoogleAds.ICreateAdGroupCriteriaInput>;
  export type Output = Primitive<IGoogleAds.ICreateAdGroupCriteriaOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-ads/campaigns/ads/keywords",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-ads/campaigns/ads/keywords";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IGoogleAds.ICreateAdGroupCriteriaOutput>> =>
    typia.random<Primitive<IGoogleAds.ICreateAdGroupCriteriaOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: addKeyword.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
