/**
 * @packageDocumentation
 * @module api.functional.connector.marketing_copy
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as generate_copy from "./generate_copy";
export * as generate_copy_image from "./generate_copy_image";
