/**
 * @packageDocumentation
 * @module api.functional.connector.google_sheet.header
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleSheet } from "../../../../structures/connector/google_sheet/IGoogleSheet";

/**
 * 구글 시트에 헤더를 추가합니다.
 *
 * @summary 구글 시트 헤더 추가.
 * @param input 구글 시트 url과 추가할 헤더 이름.
 * @tag Google Sheet
 * @internal
 *
 * @controller GoogleSheetController.writeHeaders
 * @path POST /connector/google-sheet/header
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function writeHeaders(
  connection: IConnection,
  input: writeHeaders.Input,
): Promise<void> {
  return !!connection.simulate
    ? writeHeaders.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...writeHeaders.METADATA,
          path: writeHeaders.path(),
        },
        input,
      );
}
export namespace writeHeaders {
  export type Input = Primitive<IGoogleSheet.IWriteGoogleSheetHeadersInput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-sheet/header",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-sheet/header";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<void>> => typia.random<Primitive<void>>(g);
  export const simulate = (
    connection: IConnection,
    input: writeHeaders.Input,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
