/**
 * @packageDocumentation
 * @module api.functional.swagger
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as update from "./update";
