/**
 * @packageDocumentation
 * @module api.functional.connector.kakao_talk.get_events
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { Try } from "../../../../../utils/createResponseForm";
import type { IKakaoTalk } from "../../../../structures/connector/kakao_talk/IKakaoTalk";

/**
 * 카카오톡 캘린더 일정을 조회합니다.
 *
 * @summary 카카오톡 캘린더 일정 조회.
 * @param input 일정 조회를 위한 DTO.
 * @returns 일정 정보 DTO.
 * @tag 카카오톡
 *
 * @controller KakaoTalkController.getEvents
 * @path POST /connector/kakao-talk/get-events
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getEvents(
  connection: IConnection,
  input: getEvents.Input,
): Promise<getEvents.Output> {
  return !!connection.simulate
    ? getEvents.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getEvents.METADATA,
          template: getEvents.METADATA.path,
          path: getEvents.path(),
        },
        input,
      );
}
export namespace getEvents {
  export type Input = Primitive<IKakaoTalk.IGetEventInput>;
  export type Output = Primitive<Try<IKakaoTalk.IGetEventOutput>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/kakao-talk/get-events",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/kakao-talk/get-events";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Try<IKakaoTalk.IGetEventOutput>>> =>
    typia.random<Primitive<Try<IKakaoTalk.IGetEventOutput>>>(g);
  export const simulate = (
    connection: IConnection,
    input: getEvents.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
