/**
 * @packageDocumentation
 * @module api.functional.connector.google_slides
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as presentations from "./presentations";
export * as get_presentations from "./get_presentations";
