/**
 * @packageDocumentation
 * @module api.functional.connector.discord.channel
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IDiscord } from "../../../../structures/connector/discord/IDiscord";

export * as message from "./message";
export * as invite from "./invite";
export * as direct_message from "./direct_message";

/**
 * 디스코드 서버에 채널을 생성합니다.
 *
 * @summary 디스코드 서버 채널 추가
 * @param input 채널 이름
 * @tag Discord Channel
 *
 * @controller DiscordController.createChannel
 * @path POST /connector/discord/channel
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createChannel(
  connection: IConnection,
  input: createChannel.Input,
): Promise<createChannel.Output> {
  return !!connection.simulate
    ? createChannel.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createChannel.METADATA,
          path: createChannel.path(),
        },
        input,
      );
}
export namespace createChannel {
  export type Input = Primitive<IDiscord.IDiscordChannelInput>;
  export type Output = Primitive<IDiscord.IDiscordChannelOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/discord/channel",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/discord/channel";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IDiscord.IDiscordChannelOutput>> =>
    typia.random<Primitive<IDiscord.IDiscordChannelOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: createChannel.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
