/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads.ads
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

/**
 * @controller GoogleAdsController.createAd
 * @path POST /connector/google-ads/ads
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createAd(
  connection: IConnection,
): Promise<createAd.Output> {
  return !!connection.simulate
    ? createAd.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...createAd.METADATA,
        template: createAd.METADATA.path,
        path: createAd.path(),
      });
}
export namespace createAd {
  export type Output = Primitive<`customers/${number}/adGroupAds/${number}`>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-ads/ads",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-ads/ads";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<`customers/${number}/adGroupAds/${number}`>> =>
    typia.random<Primitive<`customers/${number}/adGroupAds/${number}`>>(g);
  export const simulate = (connection: IConnection): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
