/**
 * @packageDocumentation
 * @module api.functional.connector.notion.get.page
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { ICommon } from "../../../../../structures/connector/common/ISecretValue";
import type { INotion } from "../../../../../structures/connector/notion/INotion";

/**
 * Read Notion Page list.
 *
 * @returns read page output list
 * @tag Notion
 *
 * @controller NotionController.readPageList
 * @path POST /connector/notion/get/page
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function readPageList(
  connection: IConnection,
  input: readPageList.Input,
): Promise<readPageList.Output> {
  return !!connection.simulate
    ? readPageList.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...readPageList.METADATA,
          path: readPageList.path(),
        },
        input,
      );
}
export namespace readPageList {
  export type Input = Primitive<ICommon.ISecret<"Notion", never>>;
  export type Output = Primitive<Array<INotion.IReadPageOutput>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/notion/get/page",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/notion/get/page";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Array<INotion.IReadPageOutput>>> =>
    typia.random<Primitive<Array<INotion.IReadPageOutput>>>(g);
  export const simulate = (
    connection: IConnection,
    input: readPageList.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
