/**
 * @packageDocumentation
 * @module api.functional.connector.chatbot.generate.hard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { Try } from "../../../../../../utils/createResponseForm";
import type { IChatbot } from "../../../../../structures/connector/chatbot/IChatbot";

/**
 * 어려움 난이도로 제작된 챗봇을 사용합니다.
 *
 * @summary 난이도 어려움 챗봇 사용
 * @param input 어려움 난이도로 제작된 챗봇을 사용하기 위한 정보
 * @returns 챗봇의 답변
 * @tag Chatbot
 *
 * @controller ChatBotController.generateHardChatbot
 * @path POST /connector/chatbot/generate/hard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function generateHardChatbot(
  connection: IConnection,
  input: generateHardChatbot.Input,
): Promise<generateHardChatbot.Output> {
  return !!connection.simulate
    ? generateHardChatbot.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...generateHardChatbot.METADATA,
          template: generateHardChatbot.METADATA.path,
          path: generateHardChatbot.path(),
        },
        input,
      );
}
export namespace generateHardChatbot {
  export type Input = Primitive<IChatbot.IChatBotHardGenerateInput>;
  export type Output = Primitive<Try<IChatbot.IChatbotGenerateOutput>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/chatbot/generate/hard",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/chatbot/generate/hard";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Try<IChatbot.IChatbotGenerateOutput>>> =>
    typia.random<Primitive<Try<IChatbot.IChatbotGenerateOutput>>>(g);
  export const simulate = (
    connection: IConnection,
    input: generateHardChatbot.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
