/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads.cutomerClientLink
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleAds } from "../../../../structures/connector/google_ads/IGoogleAds";

/**
 * 해당 구글 계정 내 광고 계정 모두에 관리자 승인 메일을 보내요
 *
 * @param input 고객 정보
 * @summary 광고 계정을 조회합니다
 * @returns 광고 계정
 *
 * @controller GoogleAdsController.publish
 * @path POST /connector/google-ads/cutomerClientLink
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function publish(
  connection: IConnection,
  input: publish.Input,
): Promise<void> {
  return !!connection.simulate
    ? publish.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...publish.METADATA,
          template: publish.METADATA.path,
          path: publish.path(),
        },
        input,
      );
}
export namespace publish {
  export type Input = Primitive<IGoogleAds.ISecret>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-ads/cutomerClientLink",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-ads/cutomerClientLink";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<void>> => typia.random<Primitive<void>>(g);
  export const simulate = (
    connection: IConnection,
    input: publish.Input,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
