/**
 * @packageDocumentation
 * @module api.functional.connector.google_slides.presentations.$export
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleSlides } from "../../../../../structures/connector/google_slides/IGoogleSlides";

export * as power_point from "./power_point";

/**
 * 구글 슬라이드 프레젠테이션을 한쇼 형식으로 내보내요!
 *
 * @param presentationId 변환할 프레젠테이션 아이디
 * @param input 인증 정보
 * @summary 프레젠테이션을 한쇼 파일로 내보내기
 * @returns 한쇼 파일을 다운로드 가능한 링크
 *
 * @controller GoogleSlidesController.hanshow
 * @path POST /connector/google-slides/presentations/:id/export/hanshow
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function hanshow(
  connection: IConnection,
  presentationId: string,
  input: hanshow.Input,
): Promise<hanshow.Output> {
  return !!connection.simulate
    ? hanshow.simulate(connection, presentationId, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...hanshow.METADATA,
          template: hanshow.METADATA.path,
          path: hanshow.path(presentationId),
        },
        input,
      );
}
export namespace hanshow {
  export type Input = Primitive<IGoogleSlides.IExportPresentationInput>;
  export type Output = Primitive<IGoogleSlides.IExportHanshowOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-slides/presentations/:id/export/hanshow",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (presentationId: string) =>
    `/connector/google-slides/presentations/${encodeURIComponent(presentationId ?? "null")}/export/hanshow`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IGoogleSlides.IExportHanshowOutput>> =>
    typia.random<Primitive<IGoogleSlides.IExportHanshowOutput>>(g);
  export const simulate = (
    connection: IConnection,
    presentationId: string,
    input: hanshow.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(presentationId),
      contentType: "application/json",
    });
    assert.param("presentationId")(() => typia.assert(presentationId));
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
