/**
 * @packageDocumentation
 * @module api.functional.connector.youtube_search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IConnector } from "../../../structures/common/IConnector";
import type { IYoutubeSearch } from "../../../structures/connector/youtube_search/IYoutubeSearch";

/**
 * 유튜브 영상 검색 결과를 가져옵니다.
 *
 * @summary 유튜브 영상 검색
 * @param input 유튜브 영상 검색을 위한 조건
 * @returns 유튜브 영상 검색 결과 목록.
 * @tag Youtube 유튜브
 *
 * @controller YoutubeSearchController.search
 * @path POST /connector/youtube-search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function search(
  connection: IConnection,
  input: search.Input,
): Promise<search.Output> {
  return !!connection.simulate
    ? search.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...search.METADATA,
          path: search.path(),
        },
        input,
      );
}
export namespace search {
  export type Input = Primitive<IYoutubeSearch.ISearchInput>;
  export type Output = Primitive<IConnector.ISearchOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/youtube-search",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/youtube-search";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IConnector.ISearchOutput>> =>
    typia.random<Primitive<IConnector.ISearchOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: search.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
