/**
 * @packageDocumentation
 * @module api.functional.connector.rag
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IRag } from "../../../structures/connector/rag/IRag";

export * as status from "./status";
export * as generate from "./generate";

/**
 * 입력된 파일에 대해 RAG 분석을 요청합니다.
 *
 * @summary RAG 분석 요청.
 * @param input 분석할 파일 정보.
 * @tag RAG
 *
 * @controller RagController.analyze
 * @path POST /connector/rag/analyze
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function analyze(
  connection: IConnection,
  input: analyze.Input,
): Promise<analyze.Output> {
  return !!connection.simulate
    ? analyze.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...analyze.METADATA,
          path: analyze.path(),
        },
        input,
      );
}
export namespace analyze {
  export type Input = Primitive<IRag.IAnalyzeInput>;
  export type Output = Primitive<IRag.IAnalysisOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/rag/analyze",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/rag/analyze";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IRag.IAnalysisOutput>> =>
    typia.random<Primitive<IRag.IAnalysisOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: analyze.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
