import core from "@nestia/core";
import { Controller } from "@nestjs/common";

import { IMarp } from "@wrtn/connector-api/lib/structures/connector/marp/IMarp";

import { ApiTags } from "@nestjs/swagger";
import { MarpProvider } from "../../../providers/connector/marp/MarpProvider";
import { RouteIcon } from "@wrtnio/decorators";

@Controller("connector/marp")
export class MarpController {
  constructor(private readonly marpProvider: MarpProvider) {}

  /**
   * Convert Marp markdown to PPT and store in S3
   *
   * When you write a markdown according to marp grammar, you convert it to create an html file that contains all of that content.
   * Because users won't know the markdown and marp grammar, this should be automatically generated by LLM, and users just need to provide the format, image, text, etc. they want.
   * So, instead of asking the user to provide marp or markdown grammar, ask for hints on how to organize the template and how to deploy it.
   * Asking the user to write according to the Marp grammar directly can be difficult, even if the other person is the developer!
   * All tasks such as making presentation materials or organizing contents with slides, such as pptx, google slides, html, markdown (marp), and hanshow, may have to go through a connector that changes marp to this pptx.
   *
   * Warning: If you put too much content on a single slide, the content may be cut out and invisible. Split the content into several slides.
   *
   * @summary Convert Marp markdown to PPT
   * @param input The Marp markdown string
   * @returns The S3 link of the converted PPT
   */
  @core.TypedRoute.Post("/convert-to-ppt")
  @RouteIcon(
    "https://ecosystem-connector.s3.ap-northeast-2.amazonaws.com/icons/marp.svg",
  )
  @ApiTags("pptx", "hanshow", "ppt", "powerpoint", "markdown", "marp")
  @ApiTags("Marp")
  async convertToPpt(
    @core.TypedBody() input: IMarp.IConvertInput,
  ): Promise<IMarp.IConvertOutput> {
    return this.marpProvider.convertToPpt(input);
  }
}
