/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads.get_customers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleAds } from "../../../../structures/connector/google_ads/IGoogleAds";

/**
 * 뤼튼에 연동된 고객의 광고 계정을 가져와요
 *
 * @param input 고객 정보
 * @summary 광고 계정을 조회합니다
 * @returns 광고 계정
 *
 * @controller GoogleAdsController.getCustomers
 * @path POST /connector/google-ads/get-customers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getCustomers(
  connection: IConnection,
  input: getCustomers.Input,
): Promise<getCustomers.Output> {
  return !!connection.simulate
    ? getCustomers.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getCustomers.METADATA,
          template: getCustomers.METADATA.path,
          path: getCustomers.path(),
        },
        input,
      );
}
export namespace getCustomers {
  export type Input = Primitive<IGoogleAds.ISecret>;
  export type Output = Primitive<IGoogleAds.IGetCustomerOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-ads/get-customers",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-ads/get-customers";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IGoogleAds.IGetCustomerOutput>> =>
    typia.random<Primitive<IGoogleAds.IGetCustomerOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: getCustomers.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
