/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads.campaign
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleAds } from "../../../../structures/connector/google_ads/IGoogleAds";

/**
 * 구글 고객 계정의 광고 캠페인을 생성해요
 *
 * @param input 캠페인 생성 조건
 * @summary 캠페인을 생성합니다
 * @returns 생성된 캠페인 정보
 *
 * @controller GoogleAdsController.createCampaign
 * @path POST /connector/google-ads/campaign
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createCampaign(
  connection: IConnection,
  input: createCampaign.Input,
): Promise<createCampaign.Output> {
  return !!connection.simulate
    ? createCampaign.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createCampaign.METADATA,
          template: createCampaign.METADATA.path,
          path: createCampaign.path(),
        },
        input,
      );
}
export namespace createCampaign {
  export type Input = Primitive<IGoogleAds.ICreateCampaignInput>;
  export type Output = Primitive<IGoogleAds.IGetCampaignsOutputResult>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-ads/campaign",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-ads/campaign";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IGoogleAds.IGetCampaignsOutputResult>> =>
    typia.random<Primitive<IGoogleAds.IGetCampaignsOutputResult>>(g);
  export const simulate = (
    connection: IConnection,
    input: createCampaign.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
