/**
 * @packageDocumentation
 * @module api.functional.connector.marketing_copy.generate_copy
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { Try } from "../../../../../utils/createResponseForm";
import type {
  IMarketingCopyGenerator,
  IMarketingCopyComponents,
} from "../../../../structures/connector/marketing/IMarketingCopyGenerator";

/**
 * 주어진 입력으로부터 마케팅 카피를 생성합니다.
 *
 * @summary 마케팅 카피 생성
 * @param input 마케팅 카피 생성을 위한 입력
 * @returns 생성된 마케팅 카피
 * @tag Llm 마케팅 카피 텍스트 생성
 *
 * @controller MarketingCopyController.generateCopy
 * @path POST /connector/marketing-copy/generate-copy
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function generateCopy(
  connection: IConnection,
  input: generateCopy.Input,
): Promise<generateCopy.Output> {
  return !!connection.simulate
    ? generateCopy.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...generateCopy.METADATA,
          template: generateCopy.METADATA.path,
          path: generateCopy.path(),
        },
        input,
      );
}
export namespace generateCopy {
  export type Input =
    Primitive<IMarketingCopyGenerator.IGenerateMarketingCopyInput>;
  export type Output = Primitive<Try<Partial<IMarketingCopyComponents>>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/marketing-copy/generate-copy",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/marketing-copy/generate-copy";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Try<Partial<IMarketingCopyComponents>>>> =>
    typia.random<Primitive<Try<Partial<IMarketingCopyComponents>>>>(g);
  export const simulate = (
    connection: IConnection,
    input: generateCopy.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
