/**
 * @packageDocumentation
 * @module api.functional.connector.image.generate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IImage } from "../../../../structures/connector/image/IImage";

/**
 * 이미지를 생성합니다.
 *
 * @summary 이미지 생성기 노드
 * @param input 이미지 생성을 위한 정보
 * @returns 생성된 이미지 Url
 *
 * @controller ImageController.generateImage
 * @path POST /connector/image/generate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function generateImage(
  connection: IConnection,
  input: generateImage.Input,
): Promise<generateImage.Output> {
  return !!connection.simulate
    ? generateImage.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...generateImage.METADATA,
          template: generateImage.METADATA.path,
          path: generateImage.path(),
        },
        input,
      );
}
export namespace generateImage {
  export type Input = Primitive<IImage.IRequest>;
  export type Output = Primitive<IImage.IResponse>;

  export const METADATA = {
    method: "POST",
    path: "/connector/image/generate",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/image/generate";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IImage.IResponse>> =>
    typia.random<Primitive<IImage.IResponse>>(g);
  export const simulate = (
    connection: IConnection,
    input: generateImage.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
