/**
 * @packageDocumentation
 * @module api.functional.connector.figma.get_files
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { Try } from "../../../../../utils/createResponseForm";
import type { IFigma } from "../../../../structures/connector/figma/IFigma";

/**
 * 피그마 파일들을 가져옵니다.
 *
 * @summary 피그마 파일 가져오기.
 * @returns 피그마 파일 목록.
 * @param input 파일을 가져오기 위한 조건 값.
 * @tag figma
 *
 * @controller FigmaController.readFiles
 * @path POST /connector/figma/get-files
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function readFiles(
  connection: IConnection,
  input: readFiles.Input,
): Promise<readFiles.Output> {
  return !!connection.simulate
    ? readFiles.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...readFiles.METADATA,
          template: readFiles.METADATA.path,
          path: readFiles.path(),
        },
        input,
      );
}
export namespace readFiles {
  export type Input = Primitive<IFigma.IReadFileInput>;
  export type Output = Primitive<Try<IFigma.IReadFileOutput>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/figma/get-files",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/figma/get-files";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Try<IFigma.IReadFileOutput>>> =>
    typia.random<Primitive<Try<IFigma.IReadFileOutput>>>(g);
  export const simulate = (
    connection: IConnection,
    input: readFiles.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
