/**
 * @packageDocumentation
 * @module api.functional.connector.typeform.duplicate_form
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { ITypeform } from "../../../../structures/connector/typeform/ITypeform";

/**
 * 워크스페이스에 존재하는 폼을 복사합니다.
 *
 * @summary 타입폼 폼 복사.
 * @param input 복사하여 새로 만들 폼 이름.
 * @returns 생성된 폼 ID, 제목, 타입.
 * @tag Typeform
 * @internal
 *
 * @controller TypeformController.duplicateExistingForm
 * @path POST /connector/typeform/duplicate-form
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function duplicateExistingForm(
  connection: IConnection,
  input: duplicateExistingForm.Input,
): Promise<duplicateExistingForm.Output> {
  return !!connection.simulate
    ? duplicateExistingForm.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...duplicateExistingForm.METADATA,
          path: duplicateExistingForm.path(),
        },
        input,
      );
}
export namespace duplicateExistingForm {
  export type Input = Primitive<ITypeform.IDuplicateExistingFormInput>;
  export type Output = Primitive<ITypeform.ICreateFormOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/typeform/duplicate-form",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/typeform/duplicate-form";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<ITypeform.ICreateFormOutput>> =>
    typia.random<Primitive<ITypeform.ICreateFormOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: duplicateExistingForm.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
