/**
 * @packageDocumentation
 * @module api.functional.connector.google_drive.file
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { ICommon } from "../../../../structures/connector/common/ISecretValue";
import type { IGoogleDrive } from "../../../../structures/connector/google_drive/IGoogleDrive";

export * as text from "./text";

/**
 * 구글 드라이브에 새로운 파일을 생성합니다.
 *
 * @summary 구글 드라이브 파일 생성.
 * @param input 생성할 파일명과 파일을 생성할 폴더 고유 ID.
 * @returns 생성된 파일 고유 ID.
 * @tag Google Drive
 *
 * @controller GoogleDriveController.createFile
 * @path POST /connector/google-drive/file
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createFile(
  connection: IConnection,
  input: createFile.Input,
): Promise<createFile.Output> {
  return !!connection.simulate
    ? createFile.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createFile.METADATA,
          path: createFile.path(),
        },
        input,
      );
}
export namespace createFile {
  export type Input = Primitive<IGoogleDrive.ICreateFileGoogleDriveInput>;
  export type Output = Primitive<IGoogleDrive.ICreateFileGoogleDriveOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-drive/file",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-drive/file";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IGoogleDrive.ICreateFileGoogleDriveOutput>> =>
    typia.random<Primitive<IGoogleDrive.ICreateFileGoogleDriveOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: createFile.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * 구글 드라이브에 있는 파일을 삭제합니다.
 *
 * @summary 구글 드라이브 파일 삭제.
 * @param id 삭제할 파일 고유 ID.
 * @tag Google Drive
 *
 * @controller GoogleDriveController.deleteFile
 * @path DELETE /connector/google-drive/file/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteFile(
  connection: IConnection,
  id: string,
  input: deleteFile.Input,
): Promise<void> {
  return !!connection.simulate
    ? deleteFile.simulate(connection, id, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...deleteFile.METADATA,
          path: deleteFile.path(id),
        },
        input,
      );
}
export namespace deleteFile {
  export type Input = Primitive<
    ICommon.ISecret<"google", ["https://www.googleapis.com/auth/drive"]>
  >;

  export const METADATA = {
    method: "DELETE",
    path: "/connector/google-drive/file/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string) =>
    `/connector/google-drive/file/${encodeURIComponent(id ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<void>> => typia.random<Primitive<void>>(g);
  export const simulate = (
    connection: IConnection,
    id: string,
    input: deleteFile.Input,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
