/**
 * @packageDocumentation
 * @module api.functional.connector.kakao_talk.get_firends
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IKakaoTalk } from "../../../../structures/connector/kakao_talk/IKakaoTalk";

/**
 * @controller KakaoTalkController.getFriends
 * @path POST /connector/kakao-talk/get-firends
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getFriends(
  connection: IConnection,
  input: getFriends.Input,
): Promise<getFriends.Output> {
  return !!connection.simulate
    ? getFriends.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getFriends.METADATA,
          path: getFriends.path(),
        },
        input,
      );
}
export namespace getFriends {
  export type Input = Primitive<IKakaoTalk.IGetFriendsInput>;
  export type Output = Primitive<IKakaoTalk.IGetFriendsOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/kakao-talk/get-firends",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/kakao-talk/get-firends";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IKakaoTalk.IGetFriendsOutput>> =>
    typia.random<Primitive<IKakaoTalk.IGetFriendsOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: getFriends.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
