/**
 * @packageDocumentation
 * @module api.functional.connector.google_drive.get.files
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleDrive } from "../../../../../structures/connector/google_drive/IGoogleDrive";

/**
 * 구글 드라이브에 있는 파일 목록을 가져옵니다.
 *
 * @summary 구글 드라이브 파일 목록 가져오기.
 * @returns 구글 드라이브 파일 목록.
 * @tag Google Drive
 *
 * @controller GoogleDriveController.fileList
 * @path POST /connector/google-drive/get/files
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function fileList(
  connection: IConnection,
  input: fileList.Input,
): Promise<fileList.Output> {
  return !!connection.simulate
    ? fileList.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...fileList.METADATA,
          path: fileList.path(),
        },
        input,
      );
}
export namespace fileList {
  export type Input = Primitive<IGoogleDrive.IFileListGoogleDriveInput>;
  export type Output = Primitive<IGoogleDrive.IFileListGoogleDriveOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-drive/get/files",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-drive/get/files";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IGoogleDrive.IFileListGoogleDriveOutput>> =>
    typia.random<Primitive<IGoogleDrive.IFileListGoogleDriveOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: fileList.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
