/**
 * @packageDocumentation
 * @module api.functional.connector.story_image_generator
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type {
  IGenerateStoryImageInput,
  IStoryImage,
} from "../../../structures/connector/story_image_generator/IStoryImageGenerator";

/**
 * 주어진 입력으로부터 이미지를 생성합니다.
 *
 * @summary 스토리 이미지 생성
 * @param input 이미지 생성을 위한 입력
 * @returns 생성된 이미지
 * @tag 스토리 이미지 생성
 *
 * @controller StoryImageGeneratorController.generateImage
 * @path POST /connector/story-image-generator
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function generateImage(
  connection: IConnection,
  input: generateImage.Input,
): Promise<generateImage.Output> {
  return !!connection.simulate
    ? generateImage.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...generateImage.METADATA,
          template: generateImage.METADATA.path,
          path: generateImage.path(),
        },
        input,
      );
}
export namespace generateImage {
  export type Input = Primitive<IGenerateStoryImageInput>;
  export type Output = Primitive<IStoryImage>;

  export const METADATA = {
    method: "POST",
    path: "/connector/story-image-generator",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/story-image-generator";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IStoryImage>> =>
    typia.random<Primitive<IStoryImage>>(g);
  export const simulate = (
    connection: IConnection,
    input: generateImage.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
