/**
 * @packageDocumentation
 * @module api.functional.connector.work24
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as job_openings from "./job_openings";
