/**
 * @packageDocumentation
 * @module api.functional.connector.google_drive.get.folders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { ICommon } from "../../../../../structures/connector/common/ISecretValue";
import type { IGoogleDrive } from "../../../../../structures/connector/google_drive/IGoogleDrive";

/**
 * 구글 드라이브에 있는 폴더 목록을 가져옵니다.
 *
 * @summary 구글 드라이브 폴더 목록 가져오기.
 * @returns 구글 드라이브 폴더 목록.
 * @tag Google Drive
 *
 * @controller GoogleDriveController.folderList
 * @path POST /connector/google-drive/get/folders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function folderList(
  connection: IConnection,
  input: folderList.Input,
): Promise<folderList.Output> {
  return !!connection.simulate
    ? folderList.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...folderList.METADATA,
          path: folderList.path(),
        },
        input,
      );
}
export namespace folderList {
  export type Input = Primitive<
    ICommon.ISecret<"google", ["https://www.googleapis.com/auth/drive"]>
  >;
  export type Output = Primitive<IGoogleDrive.IFolderListGoogleDriveOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-drive/get/folders",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-drive/get/folders";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IGoogleDrive.IFolderListGoogleDriveOutput>> =>
    typia.random<Primitive<IGoogleDrive.IFolderListGoogleDriveOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: folderList.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
