#!/usr/bin/env sh
. "$(dirname -- "$0")/husky.sh"

if ! which npm > /dev/null;
  then
    echo
    echo 'You should run the package installation since there are changes in the package locking file.'
    echo 'Please install npm first, and put the command below:'
    echo
    echo 'npm ci'
    echo
    exit 0
fi;

# 현재 `HEAD` 포인터와 병합하기 전 `HEAD(ORIG_HEAD)` 포인터 사이에 변경된 파일 목록 중 `package-lock.json` 파일이 있는지 확인
if [[ $(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD) =~ 'package-lock.json' ]];
  then # `npm.lock` 파일이 변경 되었다면 의존성 설치
    echo
    echo 'The package locking file has been modified and will run the installation silently.'
    echo
    npm ci
  else
    echo
    echo 'Did not run the package installation since there are no changes in the package locking file.'
    echo
fi;