/**
 * @packageDocumentation
 * @module api.functional.connector.notion.find_item_list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { ICommon } from "../../../../structures/connector/common/ISecretValue";
import type { INotion } from "../../../../structures/connector/notion/INotion";

/**
 * Get Database Item List.
 *
 * @param databaseId
 * @returns Database Item List
 * @tag Notion
 *
 * @controller NotionController.getDatabaseItemList
 * @path POST /connector/notion/find-item-list/:databaseId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getDatabaseItemList(
  connection: IConnection,
  input: getDatabaseItemList.Input,
  databaseId: string,
): Promise<getDatabaseItemList.Output> {
  return !!connection.simulate
    ? getDatabaseItemList.simulate(connection, input, databaseId)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getDatabaseItemList.METADATA,
          path: getDatabaseItemList.path(databaseId),
        },
        input,
      );
}
export namespace getDatabaseItemList {
  export type Input = Primitive<ICommon.ISecret<"Notion", never>>;
  export type Output = Primitive<Array<INotion.IDatabaseItemOutput>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/notion/find-item-list/:databaseId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (databaseId: string) =>
    `/connector/notion/find-item-list/${encodeURIComponent(databaseId ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Array<INotion.IDatabaseItemOutput>>> =>
    typia.random<Primitive<Array<INotion.IDatabaseItemOutput>>>(g);
  export const simulate = (
    connection: IConnection,
    input: getDatabaseItemList.Input,
    databaseId: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(databaseId),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    assert.param("databaseId")(() => typia.assert(databaseId));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
