/**
 * @packageDocumentation
 * @module api.functional.connector.google_docs.get_list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { ICommon } from "../../../../structures/connector/common/ISecretValue";
import type { IGoogleDocs } from "../../../../structures/connector/google_docs/IGoogleDocs";

/**
 * 구글 docs 목록을 가져옵니다.
 *
 * @summary 구글 docs 목록 가져오기.
 * @returns 구글 docs 목록.
 * @tag Google Docs
 *
 * @controller GoogleDocsController.list
 * @path POST /connector/google-docs/get-list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(
  connection: IConnection,
  input: list.Input,
): Promise<list.Output> {
  return !!connection.simulate
    ? list.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...list.METADATA,
          path: list.path(),
        },
        input,
      );
}
export namespace list {
  export type Input = Primitive<
    ICommon.ISecret<
      "google",
      [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/documents",
      ]
    >
  >;
  export type Output = Primitive<IGoogleDocs.IListGoogleDocsOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-docs/get-list",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-docs/get-list";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IGoogleDocs.IListGoogleDocsOutput>> =>
    typia.random<Primitive<IGoogleDocs.IListGoogleDocsOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: list.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
