/**
 * @packageDocumentation
 * @module api.functional.connector.kakao_map
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IKakaoMap } from "../../../structures/connector/kakao_map/IKakaoMap";

/**
 * 카카오맵으로 검색합니다
 *
 * @param input 검색 조건
 * @summary 카카오 맵 검색
 * @returns 검색 결과
 *
 * @controller KakaoMapController.search
 * @path POST /connector/kakao-map/search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function search(
  connection: IConnection,
  input: search.Input,
): Promise<search.Output> {
  return !!connection.simulate
    ? search.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...search.METADATA,
          template: search.METADATA.path,
          path: search.path(),
        },
        input,
      );
}
export namespace search {
  export type Input = Primitive<IKakaoMap.SearchByKeywordInput>;
  export type Output = Primitive<IKakaoMap.SearchByKeywordOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/kakao-map/search",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/kakao-map/search";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IKakaoMap.SearchByKeywordOutput>> =>
    typia.random<Primitive<IKakaoMap.SearchByKeywordOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: search.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
