/**
 * @packageDocumentation
 * @module api.functional.connector.notion.page.content
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { INotion } from "../../../../../structures/connector/notion/INotion";

/**
 * 페이지 끝에 내용을 추가합니다.
 *
 * @param input 페이지에 추가할 내용 및 추가할 페이지 정보
 * @summary 페이지에 내용 추가
 * @returns void
 * @tag Notion
 * @tag 노션
 * @tag 노트
 * @tag 메모
 * @tag 작업 관리
 * @tag 프로젝트 관리
 * @tag 할 일 목록
 * @tag 일정 관리
 * @tag 문서 작성
 * @tag 회의록 작성
 * @tag 체크리스트
 * @tag 아이디어 정리
 * @tag 업무 기록
 * @tag 학습 노트
 * @tag 스터디 플래너
 * @tag 제품기획
 * @tag 이력서
 * @tag 포트폴리오
 * @tag 협업
 * @tag 문서
 * @tag Note
 * @tag Memo
 * @tag Task Management
 * @tag Project Management
 * @tag To do list
 * @tag Schedule Management
 * @tag Document Creation
 * @tag Meeting Notes
 * @tag Checklist
 * @tag Idea Organization
 * @tag Work Logging
 * @tag Study Notes
 * @tag Study Planner
 * @tag Product Management
 * @tag Resume
 * @tag Portfolio
 * @tag Collaboration
 * @tag Document
 *
 * @controller NotionController.appendPageToContent
 * @path POST /connector/notion/page/content/:pageId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function appendPageToContent(
  connection: IConnection,
  pageId: string,
  input: appendPageToContent.Input,
): Promise<void> {
  return !!connection.simulate
    ? appendPageToContent.simulate(connection, pageId, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...appendPageToContent.METADATA,
          template: appendPageToContent.METADATA.path,
          path: appendPageToContent.path(pageId),
        },
        input,
      );
}
export namespace appendPageToContent {
  export type Input = Primitive<INotion.IAppendPageToContentInput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/notion/page/content/:pageId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (pageId: string) =>
    `/connector/notion/page/content/${encodeURIComponent(pageId ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<void>> => typia.random<Primitive<void>>(g);
  export const simulate = (
    connection: IConnection,
    pageId: string,
    input: appendPageToContent.Input,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(pageId),
      contentType: "application/json",
    });
    assert.param("pageId")(() => typia.assert(pageId));
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
