/**
 * @packageDocumentation
 * @module api.functional.connector.notion.page.content
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { INotion } from "../../../../../structures/connector/notion/INotion";

/**
 * Append Content end of Notion Page.
 *
 * @param input pageId, content
 * @returns void
 * @tag Notion
 *
 * @controller NotionController.appendPageToContent
 * @path POST /connector/notion/page/content/:pageId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function appendPageToContent(
  connection: IConnection,
  pageId: string,
  input: appendPageToContent.Input,
): Promise<void> {
  return !!connection.simulate
    ? appendPageToContent.simulate(connection, pageId, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...appendPageToContent.METADATA,
          path: appendPageToContent.path(pageId),
        },
        input,
      );
}
export namespace appendPageToContent {
  export type Input = Primitive<INotion.IAppendPageToContentInput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/notion/page/content/:pageId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (pageId: string) =>
    `/connector/notion/page/content/${encodeURIComponent(pageId ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<void>> => typia.random<Primitive<void>>(g);
  export const simulate = (
    connection: IConnection,
    pageId: string,
    input: appendPageToContent.Input,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(pageId),
      contentType: "application/json",
    });
    assert.param("pageId")(() => typia.assert(pageId));
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
