/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads.get_metrics
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleAds } from "../../../../structures/connector/google_ads/IGoogleAds";

/**
 * 구글 고객 계정 광고 당 지표를 조회해요
 *
 * @param input 광고 지표 조회 조건
 * @summary 캠페인 광고 성과(metrics)를 조회합니다
 * @returns 지표 목록
 *
 * @controller GoogleAdsController.getMetrics
 * @path POST /connector/google-ads/get-metrics
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMetrics(
  connection: IConnection,
  input: getMetrics.Input,
): Promise<getMetrics.Output> {
  return !!connection.simulate
    ? getMetrics.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getMetrics.METADATA,
          template: getMetrics.METADATA.path,
          path: getMetrics.path(),
        },
        input,
      );
}
export namespace getMetrics {
  export type Input = Primitive<IGoogleAds.IGetMetricInput>;
  export type Output = Primitive<Array<IGoogleAds.IGetMetricOutputResult>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-ads/get-metrics",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-ads/get-metrics";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Array<IGoogleAds.IGetMetricOutputResult>>> =>
    typia.random<Primitive<Array<IGoogleAds.IGetMetricOutputResult>>>(g);
  export const simulate = (
    connection: IConnection,
    input: getMetrics.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
