/**
 * @packageDocumentation
 * @module api.functional.connector.hancell
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IHancell } from "../../../structures/connector/hancell/IHancell";

/**
 * @controller HancellController.read
 * @path POST /connector/hancell/read
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function read(
  connection: IConnection,
  input: read.Input,
): Promise<read.Output> {
  return !!connection.simulate
    ? read.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...read.METADATA,
          template: read.METADATA.path,
          path: read.path(),
        },
        input,
      );
}
export namespace read {
  export type Input = Primitive<IHancell.IReadHancellInput>;
  export type Output = Primitive<IHancell.IReadHancellOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/hancell/read",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/hancell/read";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IHancell.IReadHancellOutput>> =>
    typia.random<Primitive<IHancell.IReadHancellOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: read.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
