/**
 * @packageDocumentation
 * @module api.functional.connector.google_shopping.yes_twenty_four
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleShopping } from "../../../../structures/connector/google_shopping/IGoogleShopping";

/**
 * 상품을 yes24에서 검색합니다.
 *
 * @summary yes24 검색
 * @param input 검색 조건
 * @returns 검색 결과
 *
 * @controller GoogleShoppingController.yes24
 * @path POST /connector/google-shopping/yes-twenty-four
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function yes24(
  connection: IConnection,
  input: yes24.Input,
): Promise<yes24.Output> {
  return !!connection.simulate
    ? yes24.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...yes24.METADATA,
          template: yes24.METADATA.path,
          path: yes24.path(),
        },
        input,
      );
}
export namespace yes24 {
  export type Input = Primitive<IGoogleShopping.IRequestStandAlone>;
  export type Output = Primitive<Array<IGoogleShopping.IResponse>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-shopping/yes-twenty-four",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-shopping/yes-twenty-four";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Array<IGoogleShopping.IResponse>>> =>
    typia.random<Primitive<Array<IGoogleShopping.IResponse>>>(g);
  export const simulate = (
    connection: IConnection,
    input: yes24.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
