/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads.ads.at_once
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { DeepStrictMergeHelper } from "../../../../../../utils/types/DeepStrictMerge";
import type { IGoogleAds } from "../../../../../structures/connector/google_ads/IGoogleAds";

/**
 * @controller GoogleAdsController.createAdAtOnce
 * @path POST /connector/google-ads/ads/at-once
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createAdAtOnce(
  connection: IConnection,
  input: createAdAtOnce.Input,
): Promise<createAdAtOnce.Output> {
  return !!connection.simulate
    ? createAdAtOnce.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createAdAtOnce.METADATA,
          template: createAdAtOnce.METADATA.path,
          path: createAdAtOnce.path(),
        },
        input,
      );
}
export namespace createAdAtOnce {
  export type Input = Primitive<IGoogleAds.ICreateAdGroupAdAtOnceInput>;
  export type Output = Primitive<
    DeepStrictMergeHelper<IGoogleAds.IGetCampaignsOutputResult, IGoogleAds.Ad>
  >;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-ads/ads/at-once",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-ads/ads/at-once";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<
    Primitive<
      DeepStrictMergeHelper<IGoogleAds.IGetCampaignsOutputResult, IGoogleAds.Ad>
    >
  > =>
    typia.random<
      Primitive<
        DeepStrictMergeHelper<
          IGoogleAds.IGetCampaignsOutputResult,
          IGoogleAds.Ad
        >
      >
    >(g);
  export const simulate = (
    connection: IConnection,
    input: createAdAtOnce.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
