/**
 * @packageDocumentation
 * @module api.functional.connector.google_slides.get_presentations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

/**
 * @controller GoogleSlidesController.getPresentation
 * @path POST /connector/google-slides/get-presentations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getPresentation(connection: IConnection): Promise<void> {
  return !!connection.simulate
    ? getPresentation.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getPresentation.METADATA,
        path: getPresentation.path(),
      });
}
export namespace getPresentation {
  export const METADATA = {
    method: "POST",
    path: "/connector/google-slides/get-presentations",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-slides/get-presentations";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<void>> => typia.random<Primitive<void>>(g);
  export const simulate = (connection: IConnection): void => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
