/**
 * @packageDocumentation
 * @module api.functional.connector.google_scholar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleScholar } from "../../../structures/connector/google_scholar/IGoogleScholar";

/**
 * 구글 스콜라에 있는 논문 목록을 가져옵니다.
 *
 * @summary 구글 스콜라 논문 목록 검색
 * @param input 구글 스콜라 논문 검색 조건
 * @returns 구글 스콜라 논문 목록
 * @tag Google Scholar 학술자료 사이트
 *
 * @controller GoogleScholarController.search
 * @path POST /connector/google-scholar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function search(
  connection: IConnection,
  input: search.Input,
): Promise<search.Output> {
  return !!connection.simulate
    ? search.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...search.METADATA,
          path: search.path(),
        },
        input,
      );
}
export namespace search {
  export type Input = Primitive<IGoogleScholar.ISearchInput>;
  export type Output = Primitive<Array<IGoogleScholar.ISearchOutput>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-scholar",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-scholar";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Array<IGoogleScholar.ISearchOutput>>> =>
    typia.random<Primitive<Array<IGoogleScholar.ISearchOutput>>>(g);
  export const simulate = (
    connection: IConnection,
    input: search.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
