/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as generateKeywordIdeas from "./generateKeywordIdeas";
export * as cutomerClientLink from "./cutomerClientLink";
export * as get_customers from "./get_customers";
export * as get_campaigns from "./get_campaigns";
export * as get_ad_groups from "./get_ad_groups";
export * as get_ads from "./get_ads";
export * as campaigns from "./campaigns";
export * as search_ads from "./search_ads";
export * as display_ads from "./display_ads";
