/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as generateKeywordIdeas from "./generateKeywordIdeas";
