/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as generateKeywordIdeas from "./generateKeywordIdeas";
export * as get_campaigns from "./get_campaigns";
export * as campaign from "./campaign";
export * as get_customers from "./get_customers";
