/**
 * @packageDocumentation
 * @module api.functional.connector.aws
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as file from "./file";
