/**
 * @packageDocumentation
 * @module api.functional.connector.notion.get_page_by_title
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { Try } from "../../../../../utils/createResponseForm";
import type { INotion } from "../../../../structures/connector/notion/INotion";

/**
 * 제목으로 페이지를 검색합니다.
 *
 * @summary 제목으로 페이지 검색
 * @param input 페이지 제목
 * @returns 검색된 페이지 정보
 * @tag Notion
 * @tag 노션
 * @tag 노트
 * @tag 메모
 * @tag 작업 관리
 * @tag 프로젝트 관리
 * @tag 할 일 목록
 * @tag 일정 관리
 * @tag 문서 작성
 * @tag 회의록 작성
 * @tag 체크리스트
 * @tag 아이디어 정리
 * @tag 업무 기록
 * @tag 학습 노트
 * @tag 스터디 플래너
 * @tag 제품기획
 * @tag 이력서
 * @tag 포트폴리오
 * @tag 협업
 * @tag 문서
 * @tag Note
 * @tag Memo
 * @tag Task Management
 * @tag Project Management
 * @tag To do list
 * @tag Schedule Management
 * @tag Document Creation
 * @tag Meeting Notes
 * @tag Checklist
 * @tag Idea Organization
 * @tag Work Logging
 * @tag Study Notes
 * @tag Study Planner
 * @tag Product Management
 * @tag Resume
 * @tag Portfolio
 * @tag Collaboration
 * @tag Document
 *
 * @controller NotionController.getPageByTitle
 * @path POST /connector/notion/get-page-by-title
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getPageByTitle(
  connection: IConnection,
  input: getPageByTitle.Input,
): Promise<getPageByTitle.Output> {
  return !!connection.simulate
    ? getPageByTitle.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getPageByTitle.METADATA,
          template: getPageByTitle.METADATA.path,
          path: getPageByTitle.path(),
        },
        input,
      );
}
export namespace getPageByTitle {
  export type Input = Primitive<INotion.IFindPageOrDatabaseItemInput>;
  export type Output = Primitive<Try<INotion.IFindPageByTitleOutput>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/notion/get-page-by-title",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/notion/get-page-by-title";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Try<INotion.IFindPageByTitleOutput>>> =>
    typia.random<Primitive<Try<INotion.IFindPageByTitleOutput>>>(g);
  export const simulate = (
    connection: IConnection,
    input: getPageByTitle.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
