/**
 * @packageDocumentation
 * @module api.functional.connector.google_search.jumpit
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleSearch } from "../../../../structures/connector/google_search/IGoogleSearch";

/**
 * 점핏에서 채용 공고를 검색합니다.
 *
 * @summary 점핏 채용 공고 검색
 * @param input 검색 조건
 * @returns 점핏 채용 공고 검색 결과
 *
 * @controller GoogleSearchController.searchForJumpit
 * @path POST /connector/google-search/jumpit
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function searchForJumpit(
  connection: IConnection,
  input: searchForJumpit.Input,
): Promise<searchForJumpit.Output> {
  return !!connection.simulate
    ? searchForJumpit.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...searchForJumpit.METADATA,
          template: searchForJumpit.METADATA.path,
          path: searchForJumpit.path(),
        },
        input,
      );
}
export namespace searchForJumpit {
  export type Input = Primitive<IGoogleSearch.IRequest>;
  export type Output = Primitive<string | Array<IGoogleSearch.IResponse>>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-search/jumpit",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-search/jumpit";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<string | Array<IGoogleSearch.IResponse>>> =>
    typia.random<Primitive<string | Array<IGoogleSearch.IResponse>>>(g);
  export const simulate = (
    connection: IConnection,
    input: searchForJumpit.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
