/**
 * @packageDocumentation
 * @module api.functional.connector.google_calendar.quick_event
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleCalendar } from "../../../../structures/connector/google_calendar/IGoogleCalendar";

/**
 * 구글 캘린더에 빠른 이벤트를 추가합니다.
 *
 * @summary 구글 캘린더 빠른 이벤트 추가.
 * @param calendarId 이벤트를 추가할 캘린더 고유 ID.
 * @param input 이벤트를 추가할 캘린더 고유 ID, 이벤트 명.
 * @tag Google-Calendar
 * @tag 구글 캘린더
 * @tag 캘린더
 * @tag 일정 관리
 * @tag 일정 추가
 * @tag 일정 생성
 * @tag 일정 공유
 * @tag 일정 알림
 * @tag 회의 추가
 * @tag 약속 추가
 * @tag 시간 관리
 * @tag 달력
 * @tag 스케줄 관리
 * @tag 일정 조정
 * @tag 반복 일정
 * @tag 일정 동기화
 * @tag 일정 초대
 * @tag 일정 리마인더
 * @tag 캘린더 공유
 * @tag 시간표
 * @tag 구글 일정
 * @tag 스케줄러
 * @tag 이번 주 일정
 * @tag 다음 주 일정
 * @tag 월간 일정
 * @tag 개인 일정
 * @tag 팀 일정
 * @tag 회의 예약
 * @tag 업무 캘린더
 * @tag 휴가 일정
 * @tag Google Calendar
 * @tag Calendar
 * @tag Manage Schedule
 * @tag Add Event
 * @tag Create Event
 * @tag Share Event
 * @tag Event Reminder
 * @tag Add Meeting
 * @tag Add Appointment
 * @tag Time Management
 * @tag Schedule Management
 * @tag Adjust Schedule
 * @tag Recurring Event
 * @tag Sync Calendar
 * @tag Invite to Event
 * @tag Share Calendar
 * @tag Timetable
 * @tag Google Schedule
 * @tag Scheduler
 * @tag This Week's Schedule
 * @tag Next Week's Schedule
 * @tag Monthly Schedule
 * @tag Personal Schedule
 * @tag Team Schedule
 * @tag Schedule Meeting
 * @tag Work Calendar
 * @tag Vacation Schedule
 *
 * @controller GoogleCalendarController.createQuickEvent
 * @path POST /connector/google-calendar/:calendarId/quick-event
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createQuickEvent(
  connection: IConnection,
  calendarId: string,
  input: createQuickEvent.Input,
): Promise<void> {
  return !!connection.simulate
    ? createQuickEvent.simulate(connection, calendarId, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createQuickEvent.METADATA,
          template: createQuickEvent.METADATA.path,
          path: createQuickEvent.path(calendarId),
        },
        input,
      );
}
export namespace createQuickEvent {
  export type Input = Primitive<IGoogleCalendar.ICreateQuickEventInput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-calendar/:calendarId/quick-event",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (calendarId: string) =>
    `/connector/google-calendar/${encodeURIComponent(calendarId ?? "null")}/quick-event`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<void>> => typia.random<Primitive<void>>(g);
  export const simulate = (
    connection: IConnection,
    calendarId: string,
    input: createQuickEvent.Input,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(calendarId),
      contentType: "application/json",
    });
    assert.param("calendarId")(() => typia.assert(calendarId));
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
