name: website
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "nestia.config.js"
      - "website/**"
      - "website/package.json"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Root Install
        run: npm install
      - name: Secrets to Env
        run: |
          rm .env
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Build
        working-directory: website
        run: npm install && npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ./website/out
