/**
 * @packageDocumentation
 * @module api.functional.connector.google_ads.campaigns.ads.get_keywords
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IGoogleAds } from "../../../../../../structures/connector/google_ads/IGoogleAds";

/**
 * 구글 고객 계정의 광고에 검색 키워드를 추가해요
 *
 * @param input 키워드 추가 조건
 * @summary 광고에 키워드를 추가해요
 * @returns 키워드 목록
 *
 * @controller GoogleAdsController.getKeywords
 * @path POST /connector/google-ads/campaigns/ads/get-keywords
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getKeywords(
  connection: IConnection,
  input: getKeywords.Input,
): Promise<getKeywords.Output> {
  return !!connection.simulate
    ? getKeywords.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getKeywords.METADATA,
          template: getKeywords.METADATA.path,
          path: getKeywords.path(),
        },
        input,
      );
}
export namespace getKeywords {
  export type Input = Primitive<IGoogleAds.IGetKeywordsInput>;
  export type Output = Primitive<IGoogleAds.IGetKeywordsOutput>;

  export const METADATA = {
    method: "POST",
    path: "/connector/google-ads/campaigns/ads/get-keywords",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/connector/google-ads/campaigns/ads/get-keywords";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IGoogleAds.IGetKeywordsOutput>> =>
    typia.random<Primitive<IGoogleAds.IGetKeywordsOutput>>(g);
  export const simulate = (
    connection: IConnection,
    input: getKeywords.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
